-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgl+X0xKjlLlnLJncW
sgnAfnsoVPAVtFDg4bU+8Zbv4GmgCgYIKoZIzj0DAQehRANCAAT4prouIWQ89otG
vvEVUccKiwkDnpWKLWA62jvb7wEbz9f4ymoLyTp+QwuUGzK+X7B8i+87Kgzj8JuE
PwWZW3u0
-----END PRIVATE KEY-----